### ISSUE TITLE
Navbar bugs: 2px burger height; invisible current menu item text

### ISSUE THREAD

**Issue by speller** [creativetimofficial/material-kit#102]
1. Go to official docs: https://demos.creative-tim.com/material-kit/docs/2.0/components/navbar.html
2. Narrow page contents to make dropdown visible.

Issues:
1. The burger icon is 2px height.
2. Press on the burget to open the dropdown. The Home menu item text is invisible.

**Comment by speller** [comment]
![image](https://user-images.githubusercontent.com/1829515/35669819-b371e382-0779-11e8-9537-572bb213a225.png)

![image](https://user-images.githubusercontent.com/1829515/35669840-c7d7733c-0779-11e8-9bff-29fcc30a48bd.png)

**Comment by dragosct10** [comment]
Hi, @speller! Thank you for your observation. We will fix that in the next update. In the product the toggle bars are ok on the responsive only if you will put active on the nav-item the text it will be invisible when you collapse the navbar. So to fix the issue with the text invisible please go to `assets/scss/core/_responsive.scss`  on line 67 and add the following lines of code: 

```css
&.active .nav-link,
&.active .nav-link:hover,
&.active .nav-link:focus,
&.active .nav-link:active{
    background-color: rgba(236, 237, 239, 1);
    color: $black-color;
}
```

Regards,
Dragos
