### ISSUE TITLE
Add image logo to navbar 

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/material-kit#107]
Hi! To add an image to the navbar your code must look like this: 

```html
<a class="navbar-brand" href="/">
      <div class="logo-image">
            <img src="image" class="img-fluid">
      </div>
</a>
```

and in your css you have to put the following properties:

```css
  .logo-image{
    width: 46px;
    height: 46px;
    border-radius: 50%;
    overflow: hidden;
    margin-top: -6px;
}
 }
```
