### ISSUE TITLE
.container within .main-raised causes horizontal scroll due to .main-raise l/r margin

### ISSUE THREAD

**Issue by illepic** [creativetimofficial/material-kit#39]
For the Bootstrap 3 version of material-kit:

`.main-raised` needs customized `.container` sizes due to `.main-raised` adding 30 px of margin left/right, but `.container` having set, hard widths at various media queries. Screenshot:

![title here - google chrome_101](https://cloud.githubusercontent.com/assets/295127/17449286/77238430-5b0e-11e6-8b2d-6c97b3f5dd4e.png)

The solution is a set of `.container` sizes per media query inside `.main-raised` that are 60px (30px left margin, 30px right margin) smaller.

**Comment by illepic** [comment]
Here is the solution in SCSS:

````scss
$main-raised-margin: 30px;
.main-raised {
  .container {
    @include respond-to('sm') {
      width: $container-sm - $main-raised-margin * 2;
    }
    @include respond-to('md') {
      width: $container-md - $main-raised-margin * 2;
    }
    @include respond-to('lg') {
      width: $container-lg - $main-raised-margin * 2;
    }
  }
}
````

The `respond-to` mixin is this:

````scss
$breakpoints: (
  'sm': $screen-sm-min,
  'md': $screen-md-min,
  'lg': $screen-lg-min
);
@mixin respond-to($name) {
  // If the key exists in the map
  @if map-has-key($breakpoints, $name) {
    // Prints a media query based on the value
    @media screen and (min-width: #{inspect(map-get($breakpoints, $name))}) {
      @content;
    }
  }

    // If the key doesn't exist in the map
  @else {
    @warn "Unfortunately, no value could be retrieved from `#{$name}`. "
        + "Please make sure it is defined in `$breakpoints` map.";
  }
}
````
(From https://www.sitepoint.com/managing-responsive-breakpoints-sass/ and using breakpoint vars available from `_variables_bootstrap.scss`.)
