### ISSUE TITLE
how to change material icon color when color of nav changes on scrolling?

### ISSUE THREAD

**Issue by yash2code** [creativetimofficial/material-kit#75]

**Comment by alexandru-paduraru** [comment]
@yash2code you can change the color of the icon using the navbar classes like:

```css
.navbar-primary .material-icons{
color: black;
}
.navbar-transparent .material-icons{
color: white
}
```

This will have the icons white when the navbar is transparent and as soon as the navbar-transparent class is removed you will have the black color of the icon.

Best,
Alex
